export * from "./page-data/home"
export * from "./page-data/about"
export * from "./page-data/skills"
export * from "./page-data/projects"
export * from "./page-data/blogs"
export * from "./page-data/contact"
export * from "./page-data/nav-links"
export * from "./seo-metadata"